
#
# List of commands executed on ban (don't put a slash)
#  Variables:
#    %player% will be replaced with the username of the player
#    %prefix%  will be replaced with the plugin prefix
cmd-on-ban:
  - "kick %player% %prefix% \n &7This server is protected by &cKnockBackPlusPlus &7by &cHugo4715 \n &7You took %kb%% less knockback than normal."
  - "say %prefix% %player% was kicked for hacking"
  
check-time: 1.3
enable-random-checks: true
min-notify-percentage: 0.4
max-notify-times: 5
violation-lvl:
  increase: 1
  decrease: 1
  max: 3
