name: KnockbackPlusPlus
version: ${project.version}
main: tk.hugo4715.anticheat.KbPlus
author: hugo4715
softdepend:
  - ProtocolLib
commands:
  knockbackplus:
    aliases: [kbplus]
    permission: knockbackplusplus.reload
permissions:
  knockbackplusplus.reload:
    default: op